### ISSUE TITLE
请问如何搭建哦

### ISSUE THREAD

**Issue by LusiferCoder** [gitldy1013/gitldy1013.github.io#1]
请问该博客如何搭建哦

**Comment by gitldy1013** [comment]
使用vuepress就可以了

**Comment by LusiferCoder** [comment]
你好，具体有详细的搭建步骤吗？？我想学一下，麻烦了

**Comment by gitldy1013** [comment]
https://vuepress.vuejs.org/zh/ 这里看看就能搞一套 很简单

**Comment by franklinqin0** [comment]
vuepress一步步来不简单啊！可以用别人写好的theme。GitHub搜索“vuepress theme”试试看！@jinshengyong
